# Site settings
title: linuo的博客
email: nuo9021@sina.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://linuo9021.github.io/jekyll_demo" # the base hostname & protocol for your site
twitter_username: linuo
github_username:  linuo9021
host: 103.245.222.133
# Build settings
markdown: kramdown
